### PR TITLE
change prompt to `ruby` for ruby statements

### PR DESCRIPTION
**Pull request by ko1**
Instead of adding `#ruby` on the right of input Ruby expressions,
this patch changes the prompt to the `ruby`.

This patch can relax issue about #538

### CODE REVIEW

**Comment by st0012** [comment]
It looks like the prompt needs an extra space to change?

Like typing `foo`'s prompt is still `(rdbg)`. And it'll require `foo ` for the prompt to be `(ruby)`

**Comment by ko1** [comment]
Now it is intentional because can can't understand `bre` is ruby or debug command.

**Comment by st0012** [comment]
Why? Since the debugger doesn't autocomplete it, it'll only be a Ruby expression.

**Comment by st0012** [comment]
The extra space requirement already exists in master, so it's not introduced by the change. But I'm just curious about the distinguishing limitation.

**Comment by ko1** [comment]
because debugger can't understand the typing `bre` is ruby or debug command (`break`).

**Pull request merged**
