### PR TITLE
The skip_path config should also be considered in flow control commands

### PR DESCRIPTION
**Pull request by st0012**

### CODE REVIEW

**Comment by ko1** [comment]
Now, `skip_path` is designed only for `bt` command so that description says it's "UI" category.
I understand the motivation, if we skip on `step` command, should it be a `Control` category?

**Comment by st0012** [comment]
@ko1 I agree with that 👍 I've updated its category and added test case for the change.

**Comment by ko1** [comment]
`skip_nosrc` is already `CONTROL` option. wow.

**Comment by st0012** [comment]
oh I didn't notice that, good catch 👍 I've updated it too.

**Pull request merged**
