### PR TITLE
Allow assert_line_text helper to take array expectation

### PR DESCRIPTION
**Pull request by st0012**
As suggested in https://github.com/ruby/debug/pull/104#issuecomment-863797701

### CODE REVIEW

**Review by ono-max — APPROVED** [review]
Thanks!

**Comment by ko1** [comment]
Can I confirm the spec?

https://github.com/ruby/debug/pull/125/files#diff-9b998a59b2de86476be86794ffe0d672575e0d38d8b6ce30dab32ee9062267a5R23

it seems `assert_line_text([/foo/, /bar/])` only match `/foobar/`. Is it your intention?

```
text = <<EOS
foo
bar
baz
EOS

assert_line_text([/foo/, /baz/])
```

I think the above example should match.

**Comment by ko1** [comment]
Anyway, I merged it. Please make another PR for the further improvements if needed.

**Comment by ono-max** [comment]
> I think the above example should match.

Can I create a PR for it?
I need the feature for test-builder.

Thank you.

**Comment by st0012** [comment]
@ko1 I think your suggestion makes more sense 👍 
@ono-max feel free to open a PR for it. remember to also update the tests in https://github.com/ruby/debug/blob/master/test/debug/trace_test.rb though

**Pull request merged**
