### PR TITLE
Colorize frame info with irb coloring helper

### PR DESCRIPTION
**Pull request by st0012**
I figure the call identifier should use the same color as the identifier token (e.g. method name), so I used blue for it. The other 2 components' colors were arbitrarily picked.

image

### CODE REVIEW

**Comment by st0012** [comment]
I accidentally deleted the branch from my fork 😅

**Comment by ko1** [comment]
Could you survey pry and byebug for colors? If there is no problem the same colors help users.

**Comment by st0012** [comment]
@ko1 sure 👍

**Comment by st0012** [comment]
@ko1 I don't think `byebug` supports any kind of coloring. I don't see any color when I use it and I can't find anything about the color in its document. Here's its backtrace output, which is very similar to this project's but without locals.

byebug backtrace

As for `pry`, it only prints Ruby standard stacktrace and doesn't colorize it (which is not necessary imo).

pry-backtrace

**Comment by ko1** [comment]
Thank you. Let's try!

**Comment by ko1** [comment]
image

😢 

I'll check it.

**Comment by ko1** [comment]
image
`[:BLUE, :BOLD]` helps me. it is same as method name.

**Comment by ko1** [comment]
can we colorize parameters?
image

gdb sample:

image

**Comment by ko1** [comment]
Do you have white background terminal like macos default?
It's on my putty/windows appearance with white backround:

image

**Comment by st0012** [comment]
> can we colorize parameters?

yes, that's also my plan. I'd also colorize block identifier differently.

> Do you have white background terminal like macos default?

yes, I'll test different options and make an improvement on colors.

**Comment by ko1** [comment]
RED file:line is too heavy for me (it makes me some alerts).
YELLOW is fine for me, and green is also fine.

**Comment by st0012** [comment]
@ko1 ok, I'll keep it yellow and apply bold style on it too.

**Comment by st0012** [comment]
@ko1 regarding coloring parameters, what do you think about this setup?

bright
dark

**Comment by ko1** [comment]
image

on my putty terminal, bold yellow for file:line is too bright for me...

**Comment by ko1** [comment]
How about green which uses gdb?

**Comment by st0012** [comment]
@ko1 sure, let me change it 👍

**Comment by st0012** [comment]
with a background that dark, bold green is still too bright to me

截圖 2021-05-27 下午12 58 03

but green without bold looks fine

截圖 2021-05-27 下午12 59 20

截圖 2021-05-27 下午1 00 11

it's still a bit dazzling with a white bright background, but I think we won't be able to find a perfect color without adding a new color code.
截圖 2021-05-27 下午1 00 00

**Pull request merged**
