### PR TITLE
Add tests for 4aca49

### PR DESCRIPTION
**Pull request by st0012**

### CODE REVIEW

**Comment by st0012** [comment]
The tests on TCP remote mode seems to become unstable lately. I see `TIMEOUT ERROR (10 sec) on TCP/IP mode` happens in different test cases with different Ruby versions.

**Comment by ono-max** [comment]
Can you rebase this one? It seems that you are not latest version.

**Review by ono-max — APPROVED** [review]
Thanks 👍

**Comment by st0012** [comment]
@ono-max one small suggestion: don't delete comments even if it's mistaken. it's confusing when seeing the email notification but can't find the comment. you can simply edit/add another comment to correct it 🙂

**Pull request merged**
