### PR TITLE
Update remote debugging overview with table

### PR DESCRIPTION
**Pull request by st0012**
I think using a table can make this section even more easier to understand while providing more information.

**Before**

截圖 2022-04-09 23 32 05

**After**

截圖 2022-04-09 23 30 40

### CODE REVIEW

**Comment by ko1** [comment]
I didn't check nvim-dap-ruby, but is it work enough?

**Comment by st0012** [comment]
@ko1 Yes I think it already works for basic features (I didn't test it intensively though). But based on related issue reports like https://github.com/ruby/debug/issues/523, I think there are users actively using it already.

**Comment by ko1** [comment]
I'll test before merge it.

**Comment by ko1** [comment]
I couldn't try nvim-dap-ruby because of my lack of nvim knowledge...

**Comment by st0012** [comment]
I have removed NeoVim from the table.

**Pull request merged**
