### PR TITLE
Improve readme

### PR DESCRIPTION
**Pull request by st0012**
- Add command section anchor links to most usage entries.
- Add `information` and `tracing` entries to the usage section.
- Add anchor links to `binding.break` references.

### CODE REVIEW

**Comment by ko1** [comment]
I want to leave `p lvar` because it uses debug command and no confusion.

**Comment by st0012** [comment]
The point is that I don't want to make it clear that the debugger can directly evaluate a Ruby expression without `p`.
Many Rubyists that have read my debugger article may still think that it's not supported (which I updated a bit later but most people had already read it then).

**Comment by ko1** [comment]
> I want to make it clear that the debugger can directly evaluate a Ruby expression without p.

Should not described here because evaluating Ruby expression needs some description.

**Comment by st0012** [comment]
ok but currently the readme doesn't have an expression section, I think you'll add it?
I'll revert that change.

**Comment by st0012** [comment]
@ko1 sorry please hold off the merge. I'll add more anchor links.

**Comment by st0012** [comment]
@ko1 I've updated the changed and the PR description.

**Comment by st0012** [comment]
@ko1 it's ready for review now. can you give it a look?

**Comment by st0012** [comment]
@ko1 thank you!

**Pull request merged**
