### PR TITLE
Use binding's location on irb command

### PR DESCRIPTION
**Pull request by k0kubun**
## Description
This makes the debugger's `irb` command work in the same location as the current frame's location, instead of `"(rdbg)/#{f}"`. With the current implementation, commands like `whereami` don't work. The debugger shouldn't modify the source location for `irb` command.

### Before
```rb
$ ruby ~/tmp/a.rb
[1, 3] in ~/tmp/a.rb
     1| require 'debug'
=>   2| debugger
     3| puts 'hello'
=>#0    <main> at ~/tmp/a.rb:2
(rdbg) irb    # command
irb(main)[01:0]> whereami
The current context doesn't have code.
=> nil
```

It doesn't show the current location, and `whereami` doesn't work.

### After
```rb
$ ruby ~/tmp/a.rb
[1, 3] in ~/tmp/a.rb
     1| require 'debug'
=>   2| debugger
     3| puts 'hello'
=>#0    <main> at ~/tmp/a.rb:2
(rdbg) irb    # command

From: /home/k0kubun/tmp/a.rb @ line 2 :

    1: require 'debug'
 => 2: debugger
    3: puts 'hello'

irb(main)[01:0]> whereami

From: /home/k0kubun/tmp/a.rb @ line 2 :

    1: require 'debug'
 => 2: debugger
    3: puts 'hello'

=> nil
```

It shows the current location, and `whereami` works as well.

### CODE REVIEW

**Comment by ko1** [comment]
```
From: /home/k0kubun/tmp/a.rb @ line 2 :

    1: require 'debug'
 => 2: debugger
    3: puts 'hello
```

the location lines are needed? (it seems verbose)
if you know how to remove them, please tell me how.

**Comment by k0kubun** [comment]
We could add an option like `binding.irb(show_code: false)` if you wish.

**Comment by k0kubun** [comment]
If you want that behavior and agree with https://github.com/ruby/irb/pull/444, I think we can merge that on IRB's side.

**Comment by ko1** [comment]
Thank you, after releasing with [#444](https://github.com/ruby/irb/pull/444) let's update with it.
Now I merge current patch.

**Pull request merged**
