### PR TITLE
Document and reorganize ThreadClient

### PR DESCRIPTION
**Pull request by st0012**
- Similar methods are now closer together, for example `#to_s` is now next to `#inspect`.
- Command-specific methods are grouped by the command.
- Comments are added for different sections.

### CODE REVIEW

**Comment by ko1** [comment]
Maybe it is not an command (confusing with debug command), but okay (I'll change when I find another term)

**Comment by st0012** [comment]
I took the `cmd` term from 

https://github.com/ruby/debug/blob/5e7cba4eead1265f3bbbf0a5d45e25d67b150121/lib/debug/thread_client.rb#L580

It's hard to use find a proper term because the `cmd` can be either verb (`show` or `eval`) or noun (`frame` or `breakpoint`). If we can convert nouns to verbs (`frame -> switch_frame`) we can name it `action`? 

Or we can rename `cmd`  as `category`, which I think fits here but is a little too generalized.

**Comment by ko1** [comment]
ah, I see. sorry. It means message between thread and debugger (session) and message contains a command.

**Comment by st0012** [comment]
So there are:
- User commands
- Session to Thread commands

Perhaps we can name the latter as Session to Thread `instructions`?

**Comment by st0012** [comment]
I added https://github.com/ruby/debug/pull/200 as a demonstration.

**Pull request merged**
